export * from "./Home/Home";
export * from "./LoginForm/LoginForm";
export * from "./NoteFound/NoteFound";
export * from "./MovieId/MovieId";
export * from "./Register/Register";
export * from "./Watchlist/Watchlist";
export * from "./UserSettings/UserSettings";
export * from "./Account/Account";
export * from "./SearchMovie/SearchMovie";
export * from "./Popular/Popular";
export * from "./TopRated/TopRated";
export * from "./NewMovies/NewMovies";
export * from "./Upcoming/Upcoming"