export * from "./Header/Header";
export * from "./HeaderImg/HeaderImg";
export * from "./SearchBar/SearchBar";
export * from "./PosterList/PosterList";
export * from "./Poster/Poster";
export * from "./Footer/Footer";
export * from "./ButtonMovie/ButtonMovie";
export * from "./FormSearchMovie/FormSearchMovie";
export * from "./Poster/Poster";
